# yamllint disable rule:line-length
---
ITDService:
  AuthenticationAuthority: "https://localhost:44319"
  WebApiAddress: "https://localhost:44390/"
  Logging:
    LogToConsole: True
    LogToFile: True
    LogPath: 'C:\SmartSuite\Logs'
    LogFileName: 'ITDService.log'
    LogLevel: Info
    NamespaceLogLevels:
      Program: Debug
      ITDService: Debug
      BrockSolutions: Debug
      Microsoft: Info
    Rollover: True
    OutputTemplate: '${longdate} ${event-properties:item=EventId_Id:whenEmpty=0} ${level:uppercase=true} ${logger} ${message} ${exception:format=tostring}'
    OverflowAction: Block
    # SeqServerUrl: http://localhost:5341
    # SeqApiKey: hTFYSlmQucnY43tXQNOB
    # AzureInstrumentationKey: 00000000-0000-0000-0000-000000000000
  ConnectionString:
    Operational: Server=(local);database=ITDService_Operational;Integrated Security=true;MultipleActiveResultSets=true
  IsWindowsService: True
  ExampleConfigurationValue: "test123"
